export const userData = [
  {
    id: 1,
    name: "Anna Müller",
    location: "Berlin, Deutschland",
    trust: "Vertrauenswürdig",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "Vor 3 Tagen",
    description:
      "Lokalisieren Sie die Quelle des Lecks, stellen Sie die Wasserversorgung Lokalisieren Sie die Quelle des...",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Solaranlagen", "Sanitär"],
    income: "1300",
  },
  {
    id: 2,
    name: "Lukas Schreiber",
    location: "Munich, Germany",
    trust: "Vertrauenswürdig",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "12m",
    description: "Wir bieten schnelle Reparaturen an.",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Solaranlagen", "Sanitär"],
    income: "800",
  },
  {
    id: 3,
    name: "Klaus Schneider",
    location: "Rheda-Wiedenbrück",
    decription:
      "10+ Jahre Erfahrung in der Branche. Verfügbar für dringende Einsätze. Tätig in der gesamten Region rund um Rheda-Wiedenbrück.",
    trust: "Vertrauenswürdig",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "Vor 3 Tagen",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Solaranlagen", "Sanitär"],
    income: "900",
  },
  {
    id: 4,
    name: "Franco Krause",
    location: "Süddeutschland",
    description:
      "Lorem ipsum dolor sit amet consectetur. Eget lectus integer sed bibendum faucibus pulvinar. Urna justo tempus posuere lectus gravida.",
    trust: "Vertrauenswürdig",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "Vor 3 Tagen",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Solaranlagen", "Sanitär"],
    income: "1200",
  },
  {
    id: 5,
    name: "Marcus Shmidt",
    location: "Ingolstadt",
    trust: "Vertrauenswürdig",
    description:
      "Lorem ipsum dolor sit amet consectetur. Eget lectus integer sed bibendum faucibus pulvinar. Urna justo tempus posuere lectus gravida.",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "Vor 3 Tagen",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Sanitär"],
    income: "1000",
  },
  {
    id: 6,
    name: "Johannes Fischer",
    location: "Sassenberg",
    trust: "Vertrauenswürdig",
    description:
      "Lorem ipsum dolor sit amet consectetur. Eget lectus integer sed bibendum faucibus pulvinar. Urna justo tempus posuere lectus gravida.",
    map: "Auf der Karte anzeigen",
    mapAddres: "Addrese",
    timeAgo: "Vor 3 Tagen",
    type: [`Fix a leaking pipe`, "Ein undichtes Rohr reparieren"],
    time: "1:00 PM - 2:30 PM",
    reviews: "38 Bewertungen",
    services: ["Heizung", "A/C", "Solaranlagen"],
    income: "800",
  },
];
